INSERT INTO AUTOR (NOME) VALUES ('Paul Deitel');
INSERT INTO AUTOR (NOME) VALUES ('Kathy Sierra');
INSERT INTO AUTOR (NOME) VALUES ('Gabriel Torres');

INSERT INTO  LIVRO (TITULO, QUANTIDADE, AUTOR_ID) VALUES ('Use a cabeça Java', 30, 2 );
INSERT INTO  LIVRO (TITULO, QUANTIDADE, AUTOR_ID) VALUES ('Java como programar', 50, 1 );
INSERT INTO  LIVRO (TITULO, QUANTIDADE, AUTOR_ID) VALUES ('Spring boot', 20, 3 );